# Generated by Django 6.0.2 on 2026-02-28 18:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0002_book_is_available_book_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("book_title", models.CharField(max_length=200)),
                ("book_author", models.CharField(max_length=200)),
                ("book_isbn", models.CharField(max_length=13)),
                ("book_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("stripe_session_id", models.CharField(max_length=255, unique=True)),
                ("customer_email", models.EmailField(max_length=254)),
                ("amount_paid", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("fulfilled", models.BooleanField(default=False)),
                ("fulfilled_at", models.DateTimeField(blank=True, null=True)),
                ("shipping_name", models.CharField(blank=True, max_length=255)),
                (
                    "shipping_address_line1",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "shipping_address_line2",
                    models.CharField(blank=True, max_length=255),
                ),
                ("shipping_city", models.CharField(blank=True, max_length=100)),
                ("shipping_state", models.CharField(blank=True, max_length=100)),
                ("shipping_postal_code", models.CharField(blank=True, max_length=20)),
                ("shipping_country", models.CharField(blank=True, max_length=2)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
