# Generated by Django 6.0.2 on 2026-02-28 23:49

from django.db import migrations, models

import books.models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Book cover image (will be cropped to 13:18 ratio)', null=True, upload_to=books.models.book_cover_path),
        ),
    ]
