# Generated by Django 6.0.2 on 2026-03-01 00:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0004_book_cover_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="isbn",
            field=models.CharField(blank=True, max_length=13, unique=True),
        ),
    ]
