# Generated by Django 6.0.2 on 2026-03-01 01:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0005_alter_book_isbn"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="shipping_country",
        ),
    ]
