# Generated by Django 6.0.2 on 2026-03-01 02:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0008_alter_book_isbn"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="book_isbn",
            field=models.CharField(blank=True, max_length=13),
        ),
    ]
