# Generated by Django 6.0.2 on 2026-04-19 15:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0011_alter_book_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="book",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
