# Generated by Django 6.0.2 on 2026-04-19 17:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0013_tag_book_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="amazon_link",
            field=models.URLField(
                blank=True,
                help_text="Amazon affiliate link for external purchase",
                null=True,
            ),
        ),
    ]
