# Generated by Django 6.0.2 on 2026-04-19 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_book_amazon_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='worldofbooks_link',
            field=models.URLField(blank=True, help_text='World of Books affiliate link for external purchase', null=True),
        ),
    ]
